language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: "python manage.py test"
services:
  - postgresql
before_script:
  - psql -c 'drop database aclarknet;' -U postgres
  - psql -c 'create database aclarknet;' -U postgres
  - python manage.py migrate
